In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
import warnings
from sklearn.preprocessing import OneHotEncoder

warnings.filterwarnings("ignore")

data = pd.read_csv("./data.csv",index_col=0)
data.drop(['ID','Photo','Club Logo','Name','Flag','Jersey Number','Loaned From','Nationality'],axis=1,inplace=True)

Encode
=

In [2]:
data[['Contract Valid Until','Joined']].head(5)

Contract Valid Until        Joined
0                 2021   Jul 1, 2004
1                 2022  Jul 10, 2018
2                 2022   Aug 3, 2017
3                 2020   Jul 1, 2011
4                 2023  Aug 30, 2015

In [3]:
data['Contract Valid Until'].value_counts()

2019            4819
2021            4360
2020            4027
2022            1477
2023            1053
Jun 30, 2019     931
2018             886
Dec 31, 2018     144
May 31, 2019      60
Jan 1, 2019       51
2024              23
Jun 30, 2020      14
Jan 31, 2019      13
2025               7
Jan 5, 2019        6
Jan 2, 2019        6
Jan 12, 2019       5
Oct 14, 2019       5
Jan 6, 2019        4
Dec 31, 2019       3
Jan 7, 2019        3
Jan 25, 2019       3
2026               2
Nov 30, 2018       2
May 31, 2020       2
Dec 1, 2019        2
Feb 27, 2020       1
Jan 4, 2019        1
Jan 11, 2019       1
Jan 3, 2019        1
Jan 20, 2019       1
Jan 18, 2019       1
Jan 15, 2019       1
Jan 30, 2019       1
Jun 1, 2019        1
May 4, 2019        1
Name: Contract Valid Until, dtype: int64

In [4]:
data['Contract Valid Until'] = data['Contract Valid Until'].str.extract('(\d+)$')
data['Contract Valid Until'] = data['Contract Valid Until'].fillna(2019)
data['Contract Valid Until'] = data['Contract Valid Until'].astype('int')

data['Contract Valid Until'].unique()

array([2021, 2022, 2020, 2023, 2019, 2024, 2025, 2026, 2018])

In [5]:
data[data.columns[range(21,47)]].head(5)

RS    LW    LF    CF    RF    RW   LAM   CAM   RAM    LM  ...   CDM  \
0  88+2  92+2  93+2  93+2  93+2  92+2  93+2  93+2  93+2  91+2  ...  61+2   
1  91+3  89+3  90+3  90+3  90+3  89+3  88+3  88+3  88+3  88+3  ...  61+3   
2  84+3  89+3  89+3  89+3  89+3  89+3  89+3  89+3  89+3  88+3  ...  60+3   
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   
4  82+3  87+3  87+3  87+3  87+3  87+3  88+3  88+3  88+3  88+3  ...  77+3   

    RDM   RWB    LB   LCB    CB   RCB    RB Crossing Finishing  
0  61+2  64+2  59+2  47+2  47+2  47+2  59+2     84.0      95.0  
1  61+3  65+3  61+3  53+3  53+3  53+3  61+3     84.0      94.0  
2  60+3  65+3  60+3  47+3  47+3  47+3  60+3     79.0      87.0  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN     17.0      13.0  
4  77+3  77+3  73+3  66+3  66+3  66+3  73+3     93.0      82.0  

[5 rows x 26 columns]

In [6]:
data['Joined'] = data['Joined'].str.extract('(\d+)$')
data['Joined'] = data['Joined'].fillna(2018)
data['Joined'] = data['Joined'].astype('int')
data['Joined'].unique()

array([2004, 2018, 2017, 2011, 2015, 2012, 2014, 2005, 2010, 2016, 2008,
       2013, 2007, 2009, 2002, 2003, 2006, 2001, 1991, 1998, 2000, 1999])

In [7]:
colName = data.columns[range(19,45)].values
for i in range(26):
    df = data[colName[i]].str.extract('(\d+)\+(\d+)')
    df = df.fillna(0)
    df[df.columns[[0,1]]] = df[df.columns[[0,1]]].astype('int')
    data[colName[i]] = df[df.columns[0]]+df[df.columns[1]]/2
data[data.columns[range(19,45)]].head(5)

LS    ST    RS    LW    LF    CF    RF    RW   LAM   CAM  ...   LWB  \
0  89.0  89.0  89.0  93.0  94.0  94.0  94.0  93.0  94.0  94.0  ...  65.0   
1  92.5  92.5  92.5  90.5  91.5  91.5  91.5  90.5  89.5  89.5  ...  66.5   
2  85.5  85.5  85.5  90.5  90.5  90.5  90.5  90.5  90.5  90.5  ...  66.5   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4  83.5  83.5  83.5  88.5  88.5  88.5  88.5  88.5  89.5  89.5  ...  78.5   

    LDM   CDM   RDM   RWB    LB   LCB    CB   RCB    RB  
0  62.0  62.0  62.0  65.0  60.0  48.0  48.0  48.0  60.0  
1  62.5  62.5  62.5  66.5  62.5  54.5  54.5  54.5  62.5  
2  61.5  61.5  61.5  66.5  61.5  48.5  48.5  48.5  61.5  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4  78.5  78.5  78.5  78.5  74.5  67.5  67.5  67.5  74.5  

[5 rows x 26 columns]

In [8]:
data['Wage'].replace('[€K]', '', inplace=True, regex=True)
data['Value'].replace('[€KM]', '', inplace=True, regex=True)
data['Release Clause'].replace('[€KM]', '', inplace=True, regex=True)

data['Wage'] = data['Wage'].astype(float)
data['Value'] = data['Value'].astype(float)
data['Release Clause'] = data['Release Clause'].astype(float)

In [9]:
maps = {'Left':0, 'Right':1}
data['Preferred Foot'] = data['Preferred Foot'].map(maps)
data['Preferred Foot'] = data['Preferred Foot'].fillna(2)
data['Preferred Foot'].unique()

array([0., 1., 2.])

In [10]:
data[['Work Rate','Body Type','Real Face','Height','Weight']].head(5)

Work Rate   Body Type Real Face Height  Weight
0  Medium/ Medium       Messi       Yes    5'7  159lbs
1       High/ Low  C. Ronaldo       Yes    6'2  183lbs
2    High/ Medium      Neymar       Yes    5'9  150lbs
3  Medium/ Medium        Lean       Yes    6'4  168lbs
4      High/ High      Normal       Yes   5'11  154lbs

In [11]:
data['Weight'].replace('[lbs]', '', inplace=True, regex=True)
data['Weight'] = data['Weight'].astype(float)
data['Weight'] = data['Weight'].fillna(data['Weight'].mean())
data['Weight'].isnull().sum()

0

In [12]:
data[['H1','H2']] = data['Height'].str.extract("(\d+)\'(\d+)",expand=False)
data[['H1','H2']] = data[['H1','H2']].astype(float)
data['Height'] = data['H1']*12+data['H2']
data = data.drop(columns=['H1','H2'])
data['Height'].head(5)

0    67.0
1    74.0
2    69.0
3    76.0
4    71.0
Name: Height, dtype: float64

In [13]:
maps = {'No':0, 'Yes':1}
data['Real Face'] = data['Real Face'].map(maps)
data['Real Face'] = data['Real Face'].fillna(0)
data['Real Face'].unique()

array([1., 0.])

In [14]:
ATK1 = ['LS','ST','RS']
ATK2 = ['LW','LF','CF','RF','RW']
MID = ['LAM','CAM','RAM','LM','LCM','CM','RCM','RM']
BACK = ['LWB','LDM','CDM','RDM','RWB','LB','LCB','CB','RCB','RB']
GK = ['GK']

map1 = {i : 'ATK' for i in ATK1}
map2 = {i : 'Forward' for i in ATK2}
map3 = {i : 'Mid' for i in MID}
map4 = {i : 'Guard' for i in BACK}
map5 = {i : 'GK' for i in GK}
maps = dict(**map1,**map2,**map3,**map4,**map5)

data['Position'] = data['Position'].map(maps)
data['Position'] = data['Position'].fillna('None')
data['Position'].unique()

array(['Forward', 'ATK', 'GK', 'Mid', 'Guard', 'None'], dtype=object)

In [15]:
data = data.join(pd.get_dummies(data.Position))
data.drop(['Position','None'],axis=1,inplace=True)

In [16]:
maps = {'Courtois':'SpecialBody', 'C. Ronaldo':'SpecialBody', 'Akinfenwa':'SpecialBody',
        'Messi':'SpecialBody', 'Neymar':'SpecialBody', 'Shaqiri':'SpecialBody', 
       'Normal':'Normal', 'Lean':'Lean', 'Stocky':'Stocky', 'PLAYER_BODY_TYPE_25':'PLAYER_BODY_TYPE_25'}
data['Body Type'] = data['Body Type'].map(maps)
data['Body Type'].value_counts()

Normal                 10595
Lean                    6417
Stocky                  1140
SpecialBody                6
PLAYER_BODY_TYPE_25        1
Name: Body Type, dtype: int64

In [17]:
data['Body Type'] = data['Body Type'].fillna('Normal')
data = data.join(pd.get_dummies(data['Body Type']))
data.drop(['Body Type'],axis=1,inplace=True)

In [18]:
data['Work Rate'].value_counts()

Medium/ Medium    9810
High/ Medium      3173
Medium/ High      1690
High/ High        1015
Medium/ Low        850
High/ Low          699
Low/ Medium        449
Low/ High          439
Low/ Low            34
Name: Work Rate, dtype: int64

In [19]:
data['Work Rate'] = data['Work Rate'].fillna('Medium/ Medium')
data = data.join(pd.get_dummies(data['Work Rate']))
data.drop(['Work Rate'],axis=1,inplace=True)

In [20]:
data['Club'].value_counts(ascending=False)

RC Celta             33
Frosinone            33
Liverpool            33
Arsenal              33
Tottenham Hotspur    33
                     ..
Paraná               20
Botafogo             20
Sligo Rovers         19
Limerick FC          19
Derry City           18
Name: Club, Length: 651, dtype: int64

In [21]:
data['Club'] = data['Club'].fillna('Free')
data = data.join(pd.get_dummies(data['Club']))
data.drop(['Club'],axis=1,inplace=True)
data.shape

(18207, 747)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18207 entries, 0 to 18206
Columns: 747 entries, Age to Śląsk Wrocław
dtypes: float64(70), int32(2), int64(4), uint8(671)
memory usage: 22.8 MB


In [23]:
data.columns

Index(['Age', 'Overall', 'Potential', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves',
       ...
       'Wycombe Wanderers', 'Yeni Malatyaspor', 'Yeovil Town',
       'Yokohama F. Marinos', 'Zagłębie Lubin', 'Zagłębie Sosnowiec',
       'Çaykur Rizespor', 'Örebro SK', 'Östersunds FK', 'Śląsk Wrocław'],
      dtype='object', length=747)

Fillna
=

In [24]:
def missing_values_table(df):
        #计算总的缺失值
        mis_val = df.isnull().sum()
        
        #计算缺失值的百分比
        mis_val_percent = 100 * df.isnull().sum() / len(df)
   
        #把结果制成表格
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        #对列重命名，第一列：Missing Values，第二列：% of Total Values
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        #根据百分比对表格进行降序排列
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        #打印总结信息：总的列数，有数据缺失的列数
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
       
        # 返回带有缺失值信息的dataframe
        return mis_val_table_ren_columns

In [25]:
missing_values_table(data)

Your selected dataframe has 747 columns.
There are 39 columns that have missing values.


Missing Values  % of Total Values
Release Clause                      1564                8.6
Composure                             48                0.3
Strength                              48                0.3
LongShots                             48                0.3
Aggression                            48                0.3
Interceptions                         48                0.3
Positioning                           48                0.3
Vision                                48                0.3
Penalties                             48                0.3
Marking                               48                0.3
Jumping                               48                0.3
StandingTackle                        48                0.3
SlidingTackle                         48                0.3
GKDiving                              48                0.3
GKHandling                            48                0.3
GKKicking                             48                0.3
GKPositioning                         48                0.3
GKReflexes                            48                0.3
Stamina                               48                0.3
International Reputation              48                0.3
Weak Foot                             48                0.3
Dribbling                             48                0.3
Skill Moves                           48                0.3
Height                                48                0.3
Crossing                              48                0.3
Finishing                             48                0.3
HeadingAccuracy                       48                0.3
ShortPassing                          48                0.3
Volleys                               48                0.3
Curve                                 48                0.3
Balance                               48                0.3
FKAccuracy                            48                0.3
LongPassing                           48                0.3
BallControl                           48                0.3
Acceleration                          48                0.3
SprintSpeed                           48                0.3
Agility                               48                0.3
Reactions                             48                0.3
ShotPower                             48                0.3

In [26]:
data['Release Clause'].value_counts()

1.1      557
1.3      423
1.4      386
1.2      385
1.5      337
        ... 
52.1       1
65.3       1
545.0      1
791.0      1
55.3       1
Name: Release Clause, Length: 1219, dtype: int64

In [27]:
data['Release Clause'] = data['Release Clause'].fillna(1.1)
data['Release Clause'].isnull().sum()

0

In [28]:
data.dropna(inplace=True)
data.shape

(18159, 747)

In [29]:
data.to_csv("./encodeData.csv")