In [1]:
import numpy as np

In [2]:
'''
创建数组

1.  arange():    按数值范围创建，与range()相似
2.  array():     将数据转换为数组
3.  asarray():   从已有的list、tuple创建
4.  zeros():     全0数组
5.  ones():      全1数组
6.  empty():     随机数组
7.  linspace():  等差数组
8.  logspace():  等比数组
9.  eye():       单位数组
10. tile():      将数组向行列方向复制
'''

a = np.arange(5)

b = np.array([1, 2, 3, 4])

c = np.asarray((1, 2, 3))

d = np.zeros((2, 3), dtype=np.int8)

e = np.ones((3, 2), dtype=np.int8)

f = np.empty((2, 3), dtype=np.int8)

g = np.linspace(start=1, stop=10, num=10, endpoint=True, dtype=np.int8)

h = np.logspace(start=1, stop=3, num=3, endpoint=True, base=10, dtype=np.int16)

i = np.eye(2, 3)

j = np.tile(b, (2, 3))


# 显示结果
print(f"arange - 数组a: \n{a}\n")
print(f"array - 数组b: \n{b}\n")
print(f"asarray - 数组c: \n{c}\n")
print(f"zeros - 数组d: \n{d}\n")
print(f"ones - 数组e: \n{e}\n")
print(f"empty - 数组f: \n{f}\n")
print(f"linspace - 数组g: \n{g}\n")
print(f"logspace - 数组h: \n{h}\n")
print(f"eye - 数组i: \n{i}\n")
print(f"tile - 数组j: \n{j}")

arange - 数组a: 
[0 1 2 3 4]

array - 数组b: 
[1 2 3 4]

asarray - 数组c: 
[1 2 3]

zeros - 数组d: 
[[0 0 0]
 [0 0 0]]

ones - 数组e: 
[[1 1]
 [1 1]
 [1 1]]

empty - 数组f: 
[[123 105 125]
 [  0  28   2]]

linspace - 数组g: 
[ 1  2  3  4  5  6  7  8  9 10]

logspace - 数组h: 
[  10  100 1000]

eye - 数组i: 
[[1. 0. 0.]
 [0. 1. 0.]]

tile - 数组j: 
[[1 2 3 4 1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4 1 2 3 4]]


In [3]:
'''
数组的属性

1. shape:     形状
2. dtype:     数据类型
3. ndim:      维度的数量
4. size:      元素数量
5. itemsize:  数组中各个元素所占字节数
6. nbytes:    整个数组所占字节数
7. real:      实部
8. imag:      虚部
'''

print(f"待查看属性的数组: \n{a}\n")
print(f"shape-形状:                 {a.shape}")
print(f"dtype-数据类型:              {a.dtype}")
print(f"ndim-维度:                  {a.ndim}")
print(f"size-元素数量:               {a.size}")
print(f"itemsize-单个元素所占字节数:   {a.itemsize}")
print(f"nbytes-数组占用总字节数:      {a.nbytes}")
print(f"real-实部:                  {a.real}")
print(f"imag-虚部:                  {a.imag}")

待查看属性的数组: 
[0 1 2 3 4]

shape-形状:                 (5,)
dtype-数据类型:              int32
ndim-维度:                  1
size-元素数量:               5
itemsize-单个元素所占字节数:   4
nbytes-数组占用总字节数:      20
real-实部:                  [0 1 2 3 4]
imag-虚部:                  [0 0 0 0 0]


In [4]:
'''
数组的索引与切片

1. array[m: n: step]:  array可像列表那样切片
2. array[m, n]:        获取 array[m][n]位置的值 
3. 布尔索引
'''

a1 = a[::-1] # 反转数组
a2 = f[1,1]
a3 = a1.copy()
a3[(a1 >= 3) | (a1 <= 1)] = 2

print(f"初始数组a:           {a}")
print(f"反转数组a:           {a1}")
print(f"数组f的[1,1]位置的值: {a2}")
print(f"布尔索引:            {a3}")

初始数组a:           [0 1 2 3 4]
反转数组a:           [4 3 2 1 0]
数组f的[1,1]位置的值: 28
布尔索引:            [2 2 2 2 2]


In [5]:
'''
变更数组形状

1. reshape():       传入想要变换的维度即可
2. flatten():       将数组变为1维
3. ravel():         与flatten功能相同，但是返回的是视图，flatten返回真实的数组，需要分配新的内存空间
4. shape = tuple:   用元组直接定义数组形状
5. transpose:       转置
6. resize():        与reshape作用类似，但会改变原数组
'''

k = np.arange(24)
print(f"【数组 k】: \n{k}\n")
k = k.reshape(2, 3, 4)
l = k.flatten()
print(f"reshape: \n{k}\n")
print(f"flatten: \n{l}\n")

print("===============================================================")

print(f"\n【数组 g】: \n{g}\n")
g.shape = (5, 2)
m = g.transpose()
print(f"tuple: \n{g}\n")
print(f"transpose: \n{m}\n")
g.resize((2, 5))
print(f"resize: \n{g}")

【数组 k】: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

reshape: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

flatten: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


【数组 g】: 
[ 1  2  3  4  5  6  7  8  9 10]

tuple: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

transpose: 
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]

resize: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
'''
数组堆叠

1. hstack():       水平堆叠
2. vstack():       垂直堆叠
3. dstack():       深度叠加
4. concatenate():  可以选择按哪个轴的方向叠加,axis=1为水平叠加,axis=0为垂直叠加
5. column_stack(): 对一维数组以列方式堆叠，对二维数组等效于hstack
6. row_stack():    对一维数组以行方式堆叠，对二维数组等效于vstack
'''

n = np.arange(9).reshape(3,3)
o = n * 2
print(f"数组n: \n{n}\n")
print(f"数组o: \n{o}\n")


p = np.hstack((n,o))

q = np.vstack((n,o))

r = np.dstack((n,o))

s = np.concatenate((n,o),axis=1)
t = np.concatenate((n,o),axis=0)

n = n.flatten()
o = o.flatten()
u = np.column_stack((n,o))

v = np.row_stack((n,o))


print(f"hstack: \n{p}\n")
print(f"vstack: \n{q}\n")
print(f"dstack: \n{r}\n")
print(f"concatenate axis=1: \n{s}\n")
print(f"concatenate axis=0: \n{t}\n")
print("=====================将数组 n，o 进行 flatten()后==========================")
print(f"column_stack: \n{u}\n")
print(f"row_stack: \n{v}\n")

数组n: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

数组o: 
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

hstack: 
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]

vstack: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

dstack: 
[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]

concatenate axis=1: 
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]

concatenate axis=0: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

=====================将数组 n，o 进行 flatten()后==========================
column_stack: 
[[ 0  0]
 [ 1  2]
 [ 2  4]
 [ 3  6]
 [ 4  8]
 [ 5 10]
 [ 6 12]
 [ 7 14]
 [ 8 16]]

row_stack: 
[[ 0  1  2  3  4  5  6  7  8]
 [ 0  2  4  6  8 10 12 14 16]]



In [7]:
'''
数组拆分

1. hsplit():  将每列分开
2. vsplit():  将每行分开
3. split():   axis=1等效于hsplit(), axis=0等效于vsplit()
'''

w = np.arange(9).reshape(3,3)

print(f"初始数组: \n{w}\n")
print(f"hsplit: \n{np.hsplit(w, 3)}\n")
print(f"vsplit: \n{np.vsplit(w, 3)}\n")
print(f"split axis=1: \n{np.split(w, 3, axis=1)}")

初始数组: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

hsplit: 
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]

vsplit: 
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

split axis=1: 
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [8]:
'''
数组转换

1. tolist():  数组转列表
2. astype():  把数组元素转换为指定类型,如：int,'complex'等
'''

print(f"数组a: {a}\n")
print(f"tolist: {a.tolist()}\n")
print(f"astype: {a.astype('complex')}")

数组a: [0 1 2 3 4]

tolist: [0, 1, 2, 3, 4]

astype: [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j]
